### PR TITLE
Biopython 1.73

### PR DESCRIPTION
**Pull request by peterjc**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Comment by dfornika** [comment]
What's the best way to bypass that linter rule about the `license` field containing the word "License"? Is it simple to add an exception for this recipe? Or can the field in the `meta.yaml` file be edited to read "Biopython Agreement"? Would any of the following work?

"Biopython license Agreement"
"Biopython _License Agreement"
"Biopython 1icense Agreement"

**Comment by peterjc** [comment]
Thus far with this feedstock we've just ignored the linter. None of your proposed edits to the metadata seem wise.

Is there a dedicated repository for the linter? This can't be the only false positive - perhaps it just needs to report license as the final word in the license text? e.g. "Biopython License Agreement" = fine, "MIT" = fine, "MIT License"= warning.

**Comment by peterjc** [comment]
Should have merged this last month - seems something has broken in the meantime?

**Pull request merged**
