### PR TITLE
Update to Biopython 1.80

### PR DESCRIPTION
**Pull request by peterjc**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Comment by peterjc** [comment]
@conda-forge/python any suggestions? There have been changes to the C code in Biopython since the last release, but given the time lapse this could be due to a change on the conda-forge side. Thanks!

**Review by bgruening — APPROVED** [review]

**Comment by peterjc** [comment]
Fresh eyes - thank you. Was there an error message I missed, too distracted by assorting scary looking warnings?

**Comment by bgruening** [comment]
Yeah there was an error message about the missing module.

**Comment by bgruening** [comment]
Enjoy your weekend!

**Comment by peterjc** [comment]
Thank you, you too!

**Pull request merged**
