### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #17.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by dfornika** [comment]
@peterjc @nsoranzo ready to merge?

**Comment by nsoranzo** [comment]
I am not a maintainer of this feedstock, so I cannot merge.

**Comment by peterjc** [comment]
@nsoranzo do you want to be a maintainer? I'd support that.

**Comment by nsoranzo** [comment]
Thanks, if I will need to open a PR in the future I'll add myself!

**Pull request merged**
