### PR TITLE
Biopython 1.71

### PR DESCRIPTION
**Pull request by peterjc**

### CODE REVIEW

**Comment by peterjc** [comment]
I don't understand the AppVeyor failure, ``The batch file cannot be found`` under Python 2.7 and 3.6 (while 3.5 worked).

**Comment by souravsingh** [comment]
@conda-forge-admin please rerender

**Comment by souravsingh** [comment]
@peterjc conda-forge now has a bot which automatically sends a PR when there is a version bump. The bot has sent the PR here- https://github.com/conda-forge/biopython-feedstock/pull/8

**Comment by peterjc** [comment]
I like the automatic PR system - I'll know not to bother next time :)

**Pull request merged**
